notifications:
  email: false

language: python
os: linux
dist: xenial

jobs:
  include:
    - stage: lint
      name: "Black"
      language: python
      python: "3.7"
      install: pip2 install black
      script: black --check youtokentome
    
    - stage: test
      name: "Python unit tests"
      language: python
      python: "3.7"
      install:
        - pip2 install -r requirements.txt
        - python setup.py install
      script:
        - cd tests/unit_tests
        - pytest

    - stage: build
      name: "Linux wheels building"
      services:
        - docker
      language: python
      python: "3.7"
      env:
        - CIBW_SKIP="cp27-* cp33-* cp34-* *win* *i686*"
        - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2010
        - CIBW_BEFORE_BUILD="pip2 install -r requirements.txt"

    - name: "macOS wheels building"
      os: osx
      osx_image: xcode11.2
      language: shell
      compiler: clang
      env:
        - MACOSX_DEPLOYMENT_TARGET=10.14
        - CIBW_SKIP="cp27-* cp33-* cp34-* *win* *i686*"
        - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2010
        - CIBW_BEFORE_BUILD="pip2 install -r requirements.txt"
        - CXX="g++"
        - CC="gcc"

install:
  - pip2 install -U pip
  - pip2 install cibuildwheel==1.0.0 twine==1.15.0
  - pip2 install -r requirements.txt

script:
  - cibuildwheel --output-dir wheelhouse
  - ls -l wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      rm -rf dist && python setup.py sdist
      twine upload -u __token__ -p $PYPI_TOKEN --skip-existing dist/*.tar.gz wheelhouse/*.whl
    fi
